# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aeiot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semantics', models.CharField(max_length=200)),
                ('source_code', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeiot.Algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeiot.AlgorithmExecution')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeiot.Billing')),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semantics', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aeiot.Resource')),
            ],
            bases=('aeiot.resource',),
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('datacollection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aeiot.DataCollection')),
                ('data_name', models.CharField(max_length=200)),
            ],
            bases=('aeiot.datacollection',),
        ),
        migrations.CreateModel(
            name='ResultSet',
            fields=[
                ('datacollection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aeiot.DataCollection')),
                ('result_name', models.CharField(max_length=200)),
            ],
            bases=('aeiot.datacollection',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aeiot.Resource')),
            ],
            bases=('aeiot.resource',),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeiot.Resource'),
        ),
        migrations.AddField(
            model_name='billing',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeiot.Consumer'),
        ),
        migrations.AddField(
            model_name='billing',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeiot.Supplier'),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeiot.Consumer'),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeiot.Resource'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='input_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alg_input_format', to='aeiot.DataFormat'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='output_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alg_otuput_format', to='aeiot.DataFormat'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeiot.Supplier'),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeiot.DataSet'),
        ),
        migrations.AddField(
            model_name='algorithmexecution',
            name='result_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeiot.ResultSet'),
        ),
    ]
